/**
 * Vector DB LnL demo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coordinates } from './coordinates';


export interface MovieVectorVisualization { 
    id?: number;
    title?: string;
    overview?: string;
    vote_average?: number;
    vote_count?: number;
    popularity?: number;
    language?: string;
    poster_path?: string;
    document?: string;
    embedding?: Array<number>;
    similarity?: number;
    raw_similarity?: number;
    coordinates?: Coordinates;
}