/**
 * Vector DB LnL demo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Stats { 
    QBRating?: number;
    completionPct?: number;
    completions?: number;
    fumbles?: number;
    fumblesLost?: number;
    gamesPlayed?: number;
    interceptions?: number;
    longPassing?: number;
    longReception?: number;
    longRushing?: number;
    netTotalYards?: number;
    netYardsPerGame?: number;
    passingAttempts?: number;
    passingBigPlays?: number;
    passingFirstDowns?: number;
    passingTouchdowns?: number;
    passingYards?: number;
    receivingBigPlays?: number;
    receivingFirstDowns?: number;
    receivingFumbles?: number;
    receivingTargets?: number;
    receivingTouchdowns?: number;
    receivingYards?: number;
    receivingYardsAfterCatch?: number;
    receptions?: number;
    rushingAttempts?: number;
    rushingBigPlays?: number;
    rushingFirstDowns?: number;
    rushingTouchdowns?: number;
    rushingYards?: number;
    sackYardsLost?: number;
    sacks?: number;
    stuffs?: number;
    yardsPerPassAttempt?: number;
    yardsPerReception?: number;
    yardsPerRushAttempt?: number;
}

